#!/bin/sh -e
### BEGIN INIT INFO
# Provides: 		thermostat
# Required-Start: 	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Thermostat server
# Description:		Thermostat server
### END INIT INFO

DAEMON="/opt/domotherm/domotherm.py"
daemon_NAME="domotherm"

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

d_start() {
	log_daemon_msg "Starting system $daemon_NAME Daemon"
	start-stop-daemon --background --name $daemon_NAME --start --quiet --exec $DAEMON
	log_end_msg $?
}

d_stop() {
	log_daemon_msg "Stopping system $daemon_NAME Daemon"
	start-stop-daemon --stop --retry 5 --quiet --name $daemon_NAME
	log_end_msg $?
	pkill -f domotherm
}

case "$1" in

	start|stop)
		d_${1}
		;;

	restart|reload|force-reload)
		d_stop
		d_start
		;;

	force-stop)
		d_stop
		killall -q $daemon_NAME || true
		killall -q -9 $daemon_NAME || true
		;;

	status)
		status_of_proc "$daemon_NAME" "$DAEMON" "system-wide $daemon_NAME" && exit 0 || exit $?
		;;

	*)
		echo "Usage: /etc/init.d/$daemon_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
		exit 1
		;;
esac
exit 0

